lang_DE = {
    "New game": "Neues Spiel",
    "You": "Du",
    "YOU (x)": "Du (" + u"\u2715" + ")",
    "YOU (o)": "Du (" + u"\u25EF" + ")",
    "Winner: o": "Gewinner: " + u"\u25EF",
    "Winner: x": "Gewinner: " + u"\u2715",
    "Draw": "Unentschieden",
    "Bot v1.0": "Bot v1.0",
    "Bot v2.0": "Bot v2.0",
    "Bot v3.0": "Bot v3.0",
    "Bot v4.0": "Bot v4.0",
    "Invalid move. Position already occupied.": "Ungültige Position. Position schon besetzt.",
    "You lost. End of game.": "Du hast verloren. Spielende.",
}
